/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Ian' at '9/2/15 10:26 AM' with Gradle 2.5-rc-2
 *
 * @author Ian, @date 9/2/15 10:26 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
