/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Ian' at '8/28/15 8:35 AM' with Gradle 2.5-rc-2
 *
 * @author Ian, @date 8/28/15 8:35 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
